<?php
/*
Template Name: website grader
 */
get_header();
?>

<div class="container upper-z">
<div class="website-grader">
	<div class="wg" style="text-align: center;">
		<h1>TEST YOUR WEBSITE</h1>
		<div class="analyze">
			<?php echo do_shortcode('[contact-form-7 id="129" title="web grader"]' ); ?>
		</div>
	</div>
<hr>

<!-- results -->
<div class="results" style="display: none;">
	<h2 style="text-align: center;">SUMMARY:</h2>
	<div class="result2 row" >
		<div class="col-md-6 col-sm-6">
			<h3><div class="card2 score"><img src="<?php echo plugins_url();?>\contact-form-7\images\ajax-loader.gif"></div></h3>
		</div>
		<div class="col-md-6 col-sm-6">
			<h3><div class="preq card2"><img src="<?php echo plugins_url();?>\contact-form-7\images\ajax-loader.gif"></div></h3>
		</div>
	</div>

	<h2 style="text-align: center;">PERFORMANCE:</h2>
	<div class="Performance">
	<img src="<?php echo plugins_url();?>\contact-form-7\images\ajax-loader.gif">
	</div>
      <button class="download" style="display: none">Download report</button>  
</div>
</div>
</div>


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.0.272/jspdf.debug.js"></script>

<script type="text/javascript">
jQuery('#contactform').css('display','none');
document.addEventListener( 'wpcf7mailsent', function( event ) {
    doThis();
}, false );

function doThis(){
  var webs = jQuery("#wname").val();
  var key = "AIzaSyDKAeC02KcdPOHWVEZqdR1t5wwgaFJJKiM";
  var api_url ="https://www.googleapis.com/pagespeedonline/v2/runPagespeed?url="+webs+"&key="+key+"";
  jQuery.getJSON(api_url, function(data){
    var r=[];
    var score = data.ruleGroups.SPEED.score;
    var b=data.formattedResults.ruleResults;
    var ps= data.pageStats;
    var preq=ps.numberResources;
    r[0]=b.AvoidLandingPageRedirects;
    r[1]=b.EnableGzipCompression;
    r[2]=b.LeverageBrowserCaching;
    r[3]=b.MainResourceServerResponseTime;
    r[4]=b.MinifyCss;
    r[5]=b.MinifyHTML;
    r[6]=b.MinifyJavaScript;
    r[7]=b.MinimizeRenderBlockingResources;
    r[8]=b.OptimizeImages;
    r[9]=b.PrioritizeVisibleContent;

    var p="",q="",i,j,k,ri=[],ln=[],pr=[],pri=[],fr=[],fri=[];
    i=j=k=0;
    for( i=0;i<10;i++){
      ln[i]=r[i].localizedRuleName;
      ri[i]=(r[i].ruleImpact).toFixed(3);

      if(ri[i]>0){
              fr[j]=ln[i];
              fri[j++]="impact on your score "+ri[i];
              p =p+"<div class='yellow mybox'><h3>"+ln[i]+"</h3><div class='desc'> Impact on your score: "+ri[i]+"</div></div><br>";
            }
  	  else{  
              pr[k++]=ln[i];
              q =q+"<div class='green mybox'><h3>"+ln[i]+"</h3></div><br>";
            }
  	} 
  	 jQuery(".score").html("SCORE <br>"+score);
  	 jQuery(".preq").html("REQUESTS <br>"+preq);
  	 jQuery(".Performance").html("<h2 style='text-decoration:underline';>Test passed: </h2>"+q);
  	 jQuery(".Performance").append("<h2 style='text-decoration:underline';>Needs Optimization: </h2>"+p);

      jQuery('.download').on('click',function(){
          var pdf = new jsPDF();
          pdf.rect(10, 10, 190, 280);
          pdf.setFontSize(20);
          pdf.text(50,20,"Report for "+webs.substr(7));
          //summary
          pdf.setFillColor(46, 126, 190)
          pdf.circle(70, 50, 20, 'F')
          pdf.setTextColor(255, 255, 255)
          pdf.text(62, 45,"Score")
          pdf.setFontSize(25);            
          pdf.setTextColor(255, 255, 255)
          pdf.text(65,55,score+"")

          pdf.setFontSize(20);
          pdf.setFillColor(0, 0, 50, .5)
          pdf.circle(140, 50, 20, 'F')
          pdf.setTextColor(255, 255, 255)
          pdf.text(125, 45,"Requests")
          pdf.setFontSize(25) 
          pdf.setTextColor(255, 255, 255)
          pdf.text(133, 55,preq+"")

          pdf.setTextColor(0,0,0)
          // performance
          pdf.setFontSize(18);
          pdf.text(20,90,"Rules passed:");
          pdf.setFontSize(14);
          linesp=[" "];
          for(i=0;i<k;i++){ 
            linesp.push(pr[i]);
            linesp.push(" "); 
          }
          pdf.text(25,95,linesp);

          var t=115+k*10;
          pdf.setFontSize(18);
          pdf.text(20,t,"Needs Optimization:");
          pdf.setFontSize(14);          
          var lines=[" "];
          pdf.setFontSize(14);
          for(i=0;i<j;i++){
                      lines.push(fr[i]);
                      lines.push(fri[i]);
                      lines.push(" ");  
                 }
          
          pdf.text(25,t+5,lines);
          pdf.setFontSize(12);
          pdf.setTextColor(80,80,80)
          pdf.text(65,295,"Report generated by www.kilobytetech.com");
          pdf.save('my.pdf');
        });


  });
  jQuery(".results, .download").css('display','block');
}

</script> 

<?php
 get_footer();